### ISSUE TITLE
Alternate sources of same data (perhaps more frequently updated even?)

### ISSUE THREAD

**Issue by morrowc** [pavel-odintsov/asn_intelligence#1]
Did you know that UofO already provides this data in bind-zone format? or that you could query directly the DNS zone(s)?

https://www.caida.org/data/routing/routeviews-prefix2as.xml

discusses the data in question.

**Comment by morrowc** [comment]
here's a direct link to the ftp/http accessible data sets actually:
  https://publicdata.caida.org/datasets/routing/

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for sharing!

Yes, I know that many companies and organisations supply such data. It's up to customers / users to decided which one is best.

Main points of this dataset is simplicity and ability to decide data easily in any programming language plus performance of dataset file distribution.
